FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY target/simple-java-webapp-containerized-1.0.0.jar /app/simple-java-webapp-containerized-1.0.0.jar

CMD ["java", "-jar", "simple-java-webapp-containerized-1.0.0.jar"]
