FROM openjdk:17-jdk-alpine

WORKDIR /simple-java-webapp-containerized

COPY target/simple-java-webapp-containerized-1.0.0.jar /simple-java-webapp-containerized/simple-java-webapp-containerized-1.0.0.jar

CMD ["java", "-jar", "simple-java-webapp-containerized-1.0.0.jar"]
